// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvYA1YEQzrS2fiK9y8zunVW71Wrx9kBN8',
    appId: '1:821207234840:web:f885eb33d5aea922ed466d',
    messagingSenderId: '821207234840',
    projectId: 'balikin-ea5b3',
    authDomain: 'balikin-ea5b3.firebaseapp.com',
    storageBucket: 'balikin-ea5b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCklV10wvN2arZgLskTltkogLhKcRciwWs',
    appId: '1:821207234840:android:cf818491786e16b9ed466d',
    messagingSenderId: '821207234840',
    projectId: 'balikin-ea5b3',
    storageBucket: 'balikin-ea5b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvrJ5Bplkf8NL5-ODDFeuItQNS53lgjAI',
    appId: '1:821207234840:ios:eb06e1309c461c98ed466d',
    messagingSenderId: '821207234840',
    projectId: 'balikin-ea5b3',
    storageBucket: 'balikin-ea5b3.firebasestorage.app',
    androidClientId: '821207234840-pln7uidfaq06j6sgh1t0m9r343geu9r4.apps.googleusercontent.com',
    iosClientId: '821207234840-0683g6t34vdm2n4cfpqv5e77bs2e5pq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.balikin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvrJ5Bplkf8NL5-ODDFeuItQNS53lgjAI',
    appId: '1:821207234840:ios:eb06e1309c461c98ed466d',
    messagingSenderId: '821207234840',
    projectId: 'balikin-ea5b3',
    storageBucket: 'balikin-ea5b3.firebasestorage.app',
    androidClientId: '821207234840-pln7uidfaq06j6sgh1t0m9r343geu9r4.apps.googleusercontent.com',
    iosClientId: '821207234840-0683g6t34vdm2n4cfpqv5e77bs2e5pq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.balikin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvYA1YEQzrS2fiK9y8zunVW71Wrx9kBN8',
    appId: '1:821207234840:web:5da29a64610650baed466d',
    messagingSenderId: '821207234840',
    projectId: 'balikin-ea5b3',
    authDomain: 'balikin-ea5b3.firebaseapp.com',
    storageBucket: 'balikin-ea5b3.firebasestorage.app',
  );

}